### ISSUE TITLE
Quadrilaterals

### ISSUE THREAD

**Issue by eriks-aidotse** [FloSewn/TQMesh#3]
Hi!

I would like to generate 100% Quadrilateral meshes. I tried the examples, 

./TQMesh RectangleMesh.para > Mesh.dat

setting 'Element type: Quadrilateral'.

However there seems to be a few triangular elements in the mesh, see also the image on the GitHub page. What's going on?

/Erik

**Comment by FloSewn** [comment]
Hey Erik,

the current implementation of the quadrilateral paving algorithm basically generates two triangles for every advancing front edge and merges them to a quadrilateral - if possible.

However, sometimes the merging would lead to an edge intersection, or only one of two generated triangles is valid. 
In these cases, the algorithm will introduce triangles in the grid.

It might be possible to post-process these elements after the meshing process, in order to generate a pure quadrilateral mesh.

I could look at this, if needed.

Best regards

Flo

**Comment by eriks-aidotse** [comment]
Hi Flo!

Ok, I understand -it's a bit difficult. Do not spend time on this for me. But for your code it would palpably be good to offer 100% quads. 

/Erik

**Comment by FloSewn** [comment]
Hey Erik,

I just implemented the quad-refinement. 
This gives you the possibility to turn any mesh to 100% quads.

You can try it in the newest release v1.1

Maybe it helps you :-)

Best regards

Flo
