### ISSUE TITLE
Compilation in clang

### ISSUE THREAD

**Issue by ikoruk** [FloSewn/TQMesh#6]
Hi, great work! I would love to be able to use it but unfortunately the non-standard c++ and the need for g++ is a bit of an issue. Is there a plan to support compilation with clang?

**Comment by FloSewn** [comment]
Hey there,

thank you so much for your interest! 
I just changed a few things (mainly in CMakeLists.txt) so that it should now work with the clang compiler. 
At least I got it running on my system using clang++-10. 
However, the library still relies on some c++17 features, so I won't get rid of the CMAKE_CXX_STANDARD 17 flag. 

It would be great, if you could check out if it works also on your system. Let me know if there are any other problems.

Greetings 
Flo

**Comment by ikoruk** [comment]
Works great! Thank you!
